language: ruby
rvm:
  - 2.2.2
  - 2.4.9
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
