language: ruby
rvm:
  - 2.4.2 # This is the version we run currently
  - 2.4.9
  - 2.5.7
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
