version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-browsers
        environment:
          BUNDLE_JOBS: 2
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          key: allscripts-unity-client-{{ checksum "allscripts_unity_client.gemspec" }}
      - run:
          name: Bundle install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: allscripts-unity-client-{{ checksum "allscripts_unity_client.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rspec
          command: bundle exec rspec --format progress
      - run: bundle exec rubocop
